<?php
	/*
		多语言转换类，静态变量language设置当前语言，t方法转换
		t::$language = "zh_cn";
		echo t::o("home");//"首页"
	*/
	class t
	{
		//翻译方法，如language不存在，返回错误;如果在字典中没有找到，就返回$word
		public static function o($word)
		{
			if(!isset(self::$dictionary[self::$language][$word]))
			{
				//以后考虑分词后翻译
				return $word;
			}
			else
			{
				return self::$dictionary[self::$language][$word];
			}
		}
		//默认使用中文简体 zh-cn
		public static $language = "zh-cn";
		
	
		//后面要扩展语言的就只要添加到下面就可以
		private static $dictionary = array(
			"zh-cn" => array(
				'too fast' => "操作过快",
				'username or password error' => "用户名或者密码错误",
				"login success" => "登录成功",
				"empty" => "清空",
				"home" => "首页",
				"personal page"=> "个人主页",
				"account" => "账户",
				"outside home" => "外部首页",
				"logout" => "退出登录",
				"text" => "文章",
				"text manage" => "内容管理",
				"catalog" => "栏目管理",
				"page manage" => "页面管理",
				"new text" => "发表文章",
				"mailing list" => "邮件列表",
				"comment manage" => "评论管理",
				"user manage" => "用户管理",
				"profile" => "个人资料",
				"new" => "新建",
				"save" => "保存",
				"submit" => "提交",
				"reject" => "不通过",
				"approve" => "审核通过",
				"remember to click save" => "修改内容后记得点保存",
				"success" => "操作成功",
				"please select catalog" => "请选择栏目",
				"please enter title" => "请填写标题",
				"please enter content" => "请填写内容",
				"saving" => "保存中",
				"submitting" => "提交中",
				"submitted" => "已提交",
				"approved" => "已通过",
				"catalog" => "栏目",
				"title" => "标题",
				"subTitle" => "副标题",
				"title picture" => "标题图片",
				"select title picture" => "选择标题图片",
				"intro" => "简介",
				"source" => "来源",
				"keywords" => "关键字",
				"cannot change" => "不能修改",
				"text list" => "文章列表",
				"click to select" => "点击按钮进行选择",
				"picture url" => "图片地址",
				"delete" => "删除",
				"last edited" => "最后编辑",
				"not submitted" => "未提交",
				"edit" => "编辑",
				"no blank" => "不能留空",
				"varify failed" => "密码不一致",
				"wrong password" => "密码错误",
				"change password" => "修改密码",
				"old password" => "旧密码",
				"new password" => "新密码",
				"varify" => "验证",
				"confirm" => "确认",
				"cancel" => "取消",
				"basic info" => "基本信息",
				"username" => "用户名",
				"nickname" => "昵称",
				"home right column" => "首页右边栏",
				"select catalog" => "选择栏目",
				"PicSelectorWidget" => "图片滑动展示部件",
				"ActSelectorWidget" => "活动展示部件",
				"TextListSelectorWidget" => "文章列表部件",
				"CatalogRecSelectorWidget" => "子栏目推荐部件",
				"text already in list" => "文章已在列表中",
				"move up" => "上移",
				"move down" => "下移",
				"catalog intro" => "栏目简介",
				"select picture" => "选择图片",
				"delete picture" => "删除图片",
				"delete rec" => "删除此推荐",
				"options" => "设置",
				"width" => "宽度",
				"background color" => "背景颜色",
				"title font size" => "标题字体大小",
				"intro font size" => "简介字体大小",
				"rec per line" => "一行有几个推荐",
				"block height" => "块高度",
				"block interval" => "块间隔",
				"left padding" => "左边留白",
				"add in the font" => "前加一个",
				"add in the end" => "后加一个",
				"width/height" => "宽高比",
				"has bg pic" => "有背景图片",
				"mask transparency" => "蒙板透明度",
				"mask width" => "蒙板宽度",
				"title top padding" => "主标题:距离顶部",
				"subtitle top padding" => "主标题:距离顶部",
				"line width" => "行宽度",
				"font size" => "字体大小",
				"has mask" => "有蒙板",
				"pic title" => "图片标题",
				"pic subtitle" => "图片副标题",
				"link to" => "链接到",
				"text title" => "文章标题",
				"select text" => "选择文章",
				"internal" => "内部",
				"public" => "公开",
				"select" => "选择",
				"see" => "查看",
				"select text to add one" => "选择文章以添加",
				"fold" => "收起",
				"cannot select the same text again" => "不能重复选择文章",
				"no content" => "没有内容",
				"manage mailing list" => "管理邮件接收者列表",
				"add to mailing list" => "加入到接收邮件列表",
				"mailing list" => "邮件接收者列表",
				"submit" => "提交",
				"submiting" => "提交中",
				"name" => "姓名",
				"refresh" => "刷新",
				"refresh page" => "请刷新页面",
				"varify code wrong" => "验证码错误",
				"email format wrong" => "email地址格式错误",
				"varify code please" => "请输入验证码",
				"add to mailing list success" => "成功添加到接收邮件列表",
				"add to mailing list" => "添加到接收邮件列表",
				"all" => "全部",
				"check mailing history" => "查看邮件历史",
				"close" => "关闭",
				"mail options" => "邮件设置",
				"send mail" => "发送邮件",
				"email" => "电子邮件",
				"note" => "反馈",
				"share stories" => "分享故事",
				"stories" => "故事",
				"please enter email title" => "请输入邮件标题 ",
				"please select at least one receiver" => "请至少选择一个接收者",
				"confirm sending to" => "确认发送至",
				"receivers" => "接收者",
				"confirm changing mail to" => "确认切换邮件内容为",
				"viewer note" => "游客note",
				"select text for receiving viewer notes" => "选择接收读者反馈的文章",
				"send note" => "发表反馈",
				"please enter name" => "请输入名字",
				"please enter email" => "请输入email",
				"please enter content" => "请输入内容",
				"thanks" => "谢谢",
				"error, please try again" => "发生错误，请重试",
				"reply" => "回复",
				"ok" => "确定",
				"not decide" => "未审核",
				"not show" => "不展示",
				"show" => "展示",
				"latest" => "最新",
				"earliest" => "最早",
				"text link" => "文章链接",
				"time" => "时间",
				"please enter username" => "请输入用户名",
				"please enter password" => "请输入密码",
				"admin login" => "管理员登录",
				"remember me" => "记住我一周",
				"login" => "登录",
				"time" => "时间",
				"location" => "地点",
				"is class" => "是否为课程",
				"Classes" => "课程",
				"Events" => "活动",
				"About Me" => "关于我",
				"Lu Wang's Website" => "Lu Wang的个人网站",
				"Research Projects" => "研究项目",
				"Teaching" => "教学展示",
				"Resources" => "资源分享",
				"Publication" => "发表刊物",
				"Participation" => "调查参与",
				"Contact Me" => "联系信息",
				"Address" => "通信地址",
				"Zip Code" => "地区编码",
				"Email" => "电子邮件",
				"Phone" => "电话号码",
			),
			"en_us" => array(
				//leave empty
			),
		);
	}
?>